enable-magisk-update = true

parallel-jobs = 3

[YouTube]
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "anddea"
patches-version = "dev"
integrations-version = "dev"
build-mode = "both"
included-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Hide shortcuts'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Music]
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "anddea"
patches-version = "dev"
integrations-version = "dev"
build-mode = "both"
included-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom header for YouTube Music'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Twitter]
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko"
excluded-patches = "'Dynamic color'"
included-patches = "'Bring back twitter'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
apkmirror-dpi = "120-640dpi"
